# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import lbattachment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LBAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_file', models.FileField(max_length=255, upload_to=lbattachment.models.upload_attachment_file_path)),
                ('filename', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, default='', max_length=8)),
                ('is_img', models.BooleanField(default=False)),
                ('num_downloads', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
