# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourforumuserprofile',
            name='sex',
            field=models.CharField(default='Male', max_length=10, verbose_name='sex'),
        ),
    ]
