# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0002_auto_20180428_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-oid', 'created_on'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ('oid', '-created_on'), 'permissions': (('sft_mgr_forum', 'Forum-Administrator'),), 'verbose_name': 'Forum', 'verbose_name_plural': 'Forums'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'created_on', 'ordering': ('-last_reply_on',), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='topictype',
            options={'verbose_name': 'TopicType', 'verbose_name_plural': 'TopicTypes'},
        ),
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourforum.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ourforum.Topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourforum.Forum', verbose_name='Forum'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourforum.TopicType', verbose_name='TopicType'),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourforum.Forum', verbose_name='Forum'),
        ),
    ]
