# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-28 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0003_auto_20180428_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'FriendApplications'},
        ),
    ]
