# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-28 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0004_auto_20180428_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginuser',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'Users'},
        ),
    ]
