# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0006_auto_20180428_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
