# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0007_auto_20180430_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourforumuserprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
