# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0010_auto_20180501_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Notices'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
