# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0011_auto_20180501_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(verbose_name='是否赞')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourforum.Topic', verbose_name='发言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='赞用户')),
            ],
        ),
    ]
