# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0013_auto_20180510_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourforumuserprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
