# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0017_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
