# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0019_post_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('text', models.TextField(blank=True, default='', verbose_name='留言内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Bulletin_boardcontent',
                'verbose_name_plural': 'Bulletin_boardlist',
                'db_table': 'bulletinboard',
                'ordering': ['create_time'],
            },
        ),
    ]
