# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourforum', '0020_bulletin_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='status',
            new_name='is_status',
        ),
    ]
